### ISSUE TITLE
Regarding Embedding size

### ISSUE THREAD

**Issue by stripathi08** [npow/MemN2N#4]
While going through the [paper](https://arxiv.org/pdf/1503.08895.pdf), the dimension or size of the embedding (mentioned as **d** in the paper) was equal to the size of the memory vectors. 

In your implementation of the code, can you clarify how you are using the default size of embedding == 20? Was this used to pad extra null to the sentences or sequences?

**Comment by npow** [comment]
In section 4.4 it says they used `d=20` for independent training.

```
We report a variety of design choices: (i) BoW vs Position Encoding (PE) sentence representation;
(ii) training on all 20 tasks independently vs jointly training (joint training used an embedding
dimension of d = 50, while independent training used d = 20); (iii) two phase training: linear start
(LS) where softmaxes are removed initially vs training with softmaxes from the start; (iv) varying
memory hops from 1 to 3.
```

**Comment by npow** [comment]
Oops I misread your question. They're used in the dimensions of the embedding matrices `A`, `B`, `C`, and doesn't have anything to do with padding. See section 2.1 of the paper.

**Comment by stripathi08** [comment]
Okay. Thanks for your help. I did understand the concept of embedding matrices and their dimensions but got confused with how it was used to embed each word. 
As mentioned in 4.1, they have used BoW representation for embedding words but BoW represents a word via an integer and not a vector. Hence, what is the significance of these dimensions?

**Comment by stripathi08** [comment]
Or are these dimensions completely unrelated while embedding words? I think you have simply changed words to indices for representing text in the memory network.

**Comment by npow** [comment]
The term `Bag of Words` is used in the paper to indicate that the *order* of the words is not handled in the embedding of the sentence, and is not the canonical BoW where you use counts. Each word in the sentence is mapped to an index (which is the word embedding in the embedding matrix), and all the word embeddings are summed to produce a single vector representing the sentence (see section 4.1, `Sentence Representation`). In the `Positional Encoding (PE)`, `l_j` was added to the summation in order to capture the order of the words.

**Comment by stripathi08** [comment]
Okay. Thanks for the help!
